                                                                                                                                                                    
    INSERT INTO moeiwast_eiwatest_DB01.test_table (INT_NUM, NAME_STR, DBL_NUM, CREATE_DATE)                                                                                                                                                             
     VALUES ( 1, 'ƒeƒXƒg‘¾˜Y', 123.456, '2010/01/01');                                                                                                                                                               
                                                                                                                                                                    
    INSERT INTO moeiwast_eiwatest_DB01.test_table (INT_NUM, NAME_STR, DBL_NUM, CREATE_DATE)                                                                                                                                                             
     VALUES ( 2, '‚`‚a‚b‚c‚d‚e‚f', 0.456, '2013/02/02');                                                                                                                                                               
                                                                                                                                                                    
    INSERT INTO moeiwast_eiwatest_DB01.test_table (INT_NUM, NAME_STR, DBL_NUM, CREATE_DATE)                                                                                                                                                             
     VALUES ( 3, 'ABCDEFG', 999.999, '2015/03/03');                                                                                                                                                             
                                                                                                                                                                    
    INSERT INTO moeiwast_eiwatest_DB01.test_table (INT_NUM, NAME_STR, DBL_NUM, CREATE_DATE)                                                                                                                                                             
     VALUES ( 4, '‚P‚Q‚R‚S‚T‚U‚V‚W‚X‚O', null, '2015/04/04');                                                                                                                                                             
                                                                                                                                                                    
    INSERT INTO moeiwast_eiwatest_DB01.test_table (INT_NUM, NAME_STR, DBL_NUM, CREATE_DATE)                                                                                                                                                             
     VALUES ( 99999, '1234567890', 0, '2016/05/05');                                                                                                                                                                
                                                                                                                                                                    
