                                                                                                                                                                    
    INSERT INTO moeiwast_eiwatest_DB01.test01_sasada (STAFF_NO, OFFICE_CD, STAFF_NAME, WORK_TIME, CREATE_DATE)                                                                                                                                                             
     VALUES ( 10000000001, 001, '東京　太郎', 185, '2015/01/01');                                                                                                                                                               
                                                                                                                                                                    
                                                                                                                                                                    
    INSERT INTO moeiwast_eiwatest_DB01.test01_sasada (STAFF_NO, OFFICE_CD, STAFF_NAME, WORK_TIME, CREATE_DATE)                                                                                                                                                             
     VALUES ( 10000000002, 002, '千葉　次郎', 230, '2015/02/01');                                                                                                                                                               
                                                                                                                                                                    
                                                                                                                                                                    
    INSERT INTO moeiwast_eiwatest_DB01.test01_sasada (STAFF_NO, OFFICE_CD, STAFF_NAME, WORK_TIME, CREATE_DATE)                                                                                                                                                             
     VALUES ( 10000000003, 001, '神奈川　花子', 140, '2015/03/01');                                                                                                                                                               
                                                                                                                                                                    