
CREATE TABLE moeiwast_eiwatest_DB01.test01_sasada(STAFF_NO BIGINT(11), OFFICE_CD VARCHAR(3), STAFF_NAME VARCHAR(20), 
WORK_TIME INT(5), CREATE_DATE DATE,PRIMARY KEY(STAFF_NO,OFFICE_CD,STAFF_NAME)) CHARACTER SET sjis;
